controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
show_project:
    path: /project/{id}
    controller: App\Controller\PageController::showProject
    methods: ['GET']